### ISSUE TITLE
Support mission specific adaptation for defining global variables

### ISSUE THREAD

**Issue by joswig** [NASA-AMMOS/aerie-sequence-editor#5]
Missions may deliver an optional adaptation javascript file that will have hooks that Aerie can call to perform custom validation. This file will not be available at the time that Aerie is built, so we can't include it in the bundle created by vite/rollup.

The linter and content-assist functions in Aerie will call a method matching a pre-defined name, and the adaptation will return specific details about the global variables. Each global variable has a name and a type (string, int, float, enum).

Prior to our integration with the main Aerie application we should serve this as a 2nd script file. After integrating the DSL editor into Aerie this file can be returned either by Hasura, or another mechanism.

**Comment by dandelany** [comment]
Closed by PR
